name: Sync Velog Posts

on:
  schedule:
    - cron: '0 */1 * * *'  # 6시간마다 실행

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Sync Velog posts
      env:
        VELOG_API_KEY: ${{ secrets.VELOG_API_KEY }}
      run: |
        python .github/scripts/sync_velog.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Sync Velog posts" && git push)
